---
- hosts: webservers
  become: yes
  tasks:
    - name: Actualizar cache de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo en el servidor
      copy:
        content: "Este es un archivo creado por Ansible.\n"
        dest: /home/vagrant/archivo.txt

    - name: Crear una carpeta
      file:
        path: /home/vagrant/carpeta_ansible
        state: directory

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Agregar un usuario al servidor
      user:
        name: ansible_user
        state: present
        shell: /bin/bash

    - name: Ejecutar un script en el servidor
      command: /path/to/your/script.sh
